sudo: false

language: node_js

node_js:
  - 8
  - 6
  - 4

before_install:
  - npm config set spin false
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
  - node -v
  - npm -v

before_script:
  - greenkeeper-lockfile-update

script:
  - npm run test-cov

after_script:
  - npm run clean-cov
  - greenkeeper-lockfile-upload
