init:
  - git config --global core.autocrlf input

environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "3"
  - nodejs_version: "2"
  - nodejs_version: "1"
  - nodejs_version: "0.12"
  - nodejs_version: "0.11"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - IF %nodejs_version% NEQ 4 npm install -g npm@2
  - IF %nodejs_version% EQU 4 npm install -g npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install grunt-cli -g
  - npm install

test_script:
  - node --version
  - npm --version
  - ps: grunt test --no-color # PowerShell
  - cmd: grunt test --no-color

build: off
